### ISSUE TITLE
make `sparrow::corplot` returning `E` instead of `invisible(NULL)`

### ISSUE THREAD

**Issue by gladkia** [lianos/sparrow#11]
Hi Steve,

Many thanks for creating such a great package :)! 

Would it be possible to make `sparrow::corplot` returning data (i.e. `E`) instead of `invisible(NULL)`. I found the need for it while using the `sparrow::corplot` with `cluster = TRUE` and not being able to get the order of the genes.

Best,
Arek

**Comment by lianos** [comment]
sure, no problem!
