### ISSUE TITLE
seas fails when passing inputs to `ora`, & `fgsea`

### ISSUE THREAD

**Issue by RussBainer** [lianos/sparrow#15]
A thin wrapper function implemented in gCrisprTools fails when invoking the `seas` command:

https://github.com/RussBainer/gCrisprTools/blob/bfab1de2ff055e5005d8026817c4766af4c3ba9b/R/sparrow_integration.R#L185-L187

**Comment by lianos** [comment]
@RussBainer I think we fixed this one, right? If so, feel free to close.

**Comment by RussBainer** [comment]
Complete. Thanks for the attention, @lianos
